// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6gSr0ehWBS9HgVStKs9q1Wqj6cV9JH40',
    appId: '1:27918440374:web:dd8328b19c4c02dcde1317',
    messagingSenderId: '27918440374',
    projectId: 'modernlogin-ef793',
    authDomain: 'modernlogin-ef793.firebaseapp.com',
    storageBucket: 'modernlogin-ef793.appspot.com',
    measurementId: 'G-3SNEFYYNCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvSLjHL4QRD2lXuHiVDuwC4pIvbeEI6gg',
    appId: '1:27918440374:android:f6a6f9176636906ade1317',
    messagingSenderId: '27918440374',
    projectId: 'modernlogin-ef793',
    storageBucket: 'modernlogin-ef793.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFx-37IUY-oGKzgFBhlTjLUbTXuHrlfrw',
    appId: '1:27918440374:ios:5aabed10bad31bf1de1317',
    messagingSenderId: '27918440374',
    projectId: 'modernlogin-ef793',
    storageBucket: 'modernlogin-ef793.appspot.com',
    androidClientId: '27918440374-ptqklg7kle1l2n03es4eo41kbivmduvf.apps.googleusercontent.com',
    iosClientId: '27918440374-gml09e6ottns76ahae0n89f9oi49j5a1.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFx-37IUY-oGKzgFBhlTjLUbTXuHrlfrw',
    appId: '1:27918440374:ios:5aabed10bad31bf1de1317',
    messagingSenderId: '27918440374',
    projectId: 'modernlogin-ef793',
    storageBucket: 'modernlogin-ef793.appspot.com',
    androidClientId: '27918440374-ptqklg7kle1l2n03es4eo41kbivmduvf.apps.googleusercontent.com',
    iosClientId: '27918440374-gml09e6ottns76ahae0n89f9oi49j5a1.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6gSr0ehWBS9HgVStKs9q1Wqj6cV9JH40',
    appId: '1:27918440374:web:98b45662d86ab546de1317',
    messagingSenderId: '27918440374',
    projectId: 'modernlogin-ef793',
    authDomain: 'modernlogin-ef793.firebaseapp.com',
    storageBucket: 'modernlogin-ef793.appspot.com',
    measurementId: 'G-J3QJ0991BS',
  );
}
